# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05702439c09a94f28f5a32178550453f91e97feb82dc82b52553384e2bf7d897945510dc6a6fdf65fbfd23306a62cc479459236f7082844a7f8b255ca95b0316

test:
  secret_key_base: 0556e3626fe4263536efd4e63813b65e1569f068eedd64ac915c241787f2f7523f0eeaf9a4ee70c7d802c136c2b2a2ae03461be8899808c7f8ea0a4a1d91bb47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
